/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RightsRouteImport } from './routes/rights'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DistributionRouteImport } from './routes/distribution'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracksIdRouteImport } from './routes/tracks.$id'
import { Route as ReleasesIdRouteImport } from './routes/releases.$id'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminQueuesRouteImport } from './routes/admin.queues'
import { Route as AdminProcessingMetricsRouteImport } from './routes/admin.processing-metrics'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminDiagnosticsRouteImport } from './routes/admin.diagnostics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminApiUsageRouteImport } from './routes/admin.api-usage'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RightsRoute = RightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DistributionRoute = DistributionRouteImport.update({
  id: '/distribution',
  path: '/distribution',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIdRoute = TracksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TracksRoute,
} as any)
const ReleasesIdRoute = ReleasesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReleasesRoute,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtistsRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueuesRoute = AdminQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcessingMetricsRoute = AdminProcessingMetricsRouteImport.update({
  id: '/processing-metrics',
  path: '/processing-metrics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiagnosticsRoute = AdminDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiUsageRoute = AdminApiUsageRouteImport.update({
  id: '/api-usage',
  path: '/api-usage',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/distribution': typeof DistributionRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/playlists': typeof PlaylistsRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/releases': typeof ReleasesRouteWithChildren
  '/rights': typeof RightsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/tracks': typeof TracksRouteWithChildren
  '/uploads': typeof UploadsRoute
  '/admin/api-usage': typeof AdminApiUsageRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/processing-metrics': typeof AdminProcessingMetricsRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/releases/$id': typeof ReleasesIdRoute
  '/tracks/$id': typeof TracksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/distribution': typeof DistributionRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/playlists': typeof PlaylistsRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/releases': typeof ReleasesRouteWithChildren
  '/rights': typeof RightsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/tracks': typeof TracksRouteWithChildren
  '/uploads': typeof UploadsRoute
  '/admin/api-usage': typeof AdminApiUsageRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/processing-metrics': typeof AdminProcessingMetricsRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/releases/$id': typeof ReleasesIdRoute
  '/tracks/$id': typeof TracksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/albums': typeof AlbumsRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/distribution': typeof DistributionRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/playlists': typeof PlaylistsRoute
  '/processing': typeof ProcessingRoute
  '/profile': typeof ProfileRoute
  '/releases': typeof ReleasesRouteWithChildren
  '/rights': typeof RightsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/tracks': typeof TracksRouteWithChildren
  '/uploads': typeof UploadsRoute
  '/admin/api-usage': typeof AdminApiUsageRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/diagnostics': typeof AdminDiagnosticsRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/processing-metrics': typeof AdminProcessingMetricsRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/storage': typeof AdminStorageRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/releases/$id': typeof ReleasesIdRoute
  '/tracks/$id': typeof TracksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/albums'
    | '/artists'
    | '/assets'
    | '/dashboard'
    | '/discover'
    | '/distribution'
    | '/library'
    | '/login'
    | '/organizations'
    | '/playlists'
    | '/processing'
    | '/profile'
    | '/releases'
    | '/rights'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/status'
    | '/tracks'
    | '/uploads'
    | '/admin/api-usage'
    | '/admin/audit'
    | '/admin/diagnostics'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/processing-metrics'
    | '/admin/queues'
    | '/admin/storage'
    | '/admin/workers'
    | '/artists/$id'
    | '/releases/$id'
    | '/tracks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/albums'
    | '/artists'
    | '/assets'
    | '/dashboard'
    | '/discover'
    | '/distribution'
    | '/library'
    | '/login'
    | '/organizations'
    | '/playlists'
    | '/processing'
    | '/profile'
    | '/releases'
    | '/rights'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/status'
    | '/tracks'
    | '/uploads'
    | '/admin/api-usage'
    | '/admin/audit'
    | '/admin/diagnostics'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/processing-metrics'
    | '/admin/queues'
    | '/admin/storage'
    | '/admin/workers'
    | '/artists/$id'
    | '/releases/$id'
    | '/tracks/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/albums'
    | '/artists'
    | '/assets'
    | '/dashboard'
    | '/discover'
    | '/distribution'
    | '/library'
    | '/login'
    | '/organizations'
    | '/playlists'
    | '/processing'
    | '/profile'
    | '/releases'
    | '/rights'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/sitemap.xml'
    | '/status'
    | '/tracks'
    | '/uploads'
    | '/admin/api-usage'
    | '/admin/audit'
    | '/admin/diagnostics'
    | '/admin/jobs'
    | '/admin/logs'
    | '/admin/processing-metrics'
    | '/admin/queues'
    | '/admin/storage'
    | '/admin/workers'
    | '/artists/$id'
    | '/releases/$id'
    | '/tracks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlbumsRoute: typeof AlbumsRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  DistributionRoute: typeof DistributionRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PlaylistsRoute: typeof PlaylistsRoute
  ProcessingRoute: typeof ProcessingRoute
  ProfileRoute: typeof ProfileRoute
  ReleasesRoute: typeof ReleasesRouteWithChildren
  RightsRoute: typeof RightsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TracksRoute: typeof TracksRouteWithChildren
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rights': {
      id: '/rights'
      path: '/rights'
      fullPath: '/rights'
      preLoaderRoute: typeof RightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribution': {
      id: '/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof DistributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$id': {
      id: '/tracks/$id'
      path: '/$id'
      fullPath: '/tracks/$id'
      preLoaderRoute: typeof TracksIdRouteImport
      parentRoute: typeof TracksRoute
    }
    '/releases/$id': {
      id: '/releases/$id'
      path: '/$id'
      fullPath: '/releases/$id'
      preLoaderRoute: typeof ReleasesIdRouteImport
      parentRoute: typeof ReleasesRoute
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queues': {
      id: '/admin/queues'
      path: '/queues'
      fullPath: '/admin/queues'
      preLoaderRoute: typeof AdminQueuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/processing-metrics': {
      id: '/admin/processing-metrics'
      path: '/processing-metrics'
      fullPath: '/admin/processing-metrics'
      preLoaderRoute: typeof AdminProcessingMetricsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diagnostics': {
      id: '/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AdminDiagnosticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-usage': {
      id: '/admin/api-usage'
      path: '/api-usage'
      fullPath: '/admin/api-usage'
      preLoaderRoute: typeof AdminApiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApiUsageRoute: typeof AdminApiUsageRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDiagnosticsRoute: typeof AdminDiagnosticsRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminProcessingMetricsRoute: typeof AdminProcessingMetricsRoute
  AdminQueuesRoute: typeof AdminQueuesRoute
  AdminStorageRoute: typeof AdminStorageRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiUsageRoute: AdminApiUsageRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDiagnosticsRoute: AdminDiagnosticsRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminProcessingMetricsRoute: AdminProcessingMetricsRoute,
  AdminQueuesRoute: AdminQueuesRoute,
  AdminStorageRoute: AdminStorageRoute,
  AdminWorkersRoute: AdminWorkersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArtistsRouteChildren {
  ArtistsIdRoute: typeof ArtistsIdRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsIdRoute: ArtistsIdRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface ReleasesRouteChildren {
  ReleasesIdRoute: typeof ReleasesIdRoute
}

const ReleasesRouteChildren: ReleasesRouteChildren = {
  ReleasesIdRoute: ReleasesIdRoute,
}

const ReleasesRouteWithChildren = ReleasesRoute._addFileChildren(
  ReleasesRouteChildren,
)

interface TracksRouteChildren {
  TracksIdRoute: typeof TracksIdRoute
}

const TracksRouteChildren: TracksRouteChildren = {
  TracksIdRoute: TracksIdRoute,
}

const TracksRouteWithChildren =
  TracksRoute._addFileChildren(TracksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlbumsRoute: AlbumsRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  AssetsRoute: AssetsRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  DistributionRoute: DistributionRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  PlaylistsRoute: PlaylistsRoute,
  ProcessingRoute: ProcessingRoute,
  ProfileRoute: ProfileRoute,
  ReleasesRoute: ReleasesRouteWithChildren,
  RightsRoute: RightsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TracksRoute: TracksRouteWithChildren,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
